interface WhyModalProps {
  onClose: () => void;
}

export function WhyModal({ onClose }: WhyModalProps) {
  return (
    <div
      className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 backdrop-blur-sm p-4"
      onClick={onClose}
    >
      <div
        className="w-full max-w-lg rounded-2xl border border-[var(--accent-border)] bg-[var(--bg-panel)] p-8 shadow-2xl animate-fade-in-up"
        onClick={(e) => e.stopPropagation()}
      >
        <div className="flex items-start justify-between mb-4">
          <span className="font-mono-tag text-xs text-[var(--accent-2)] uppercase tracking-widest">
            ◈ Why LearnByInterrogation?
          </span>
          <button
            onClick={onClose}
            className="text-[var(--text-dim)] hover:text-[var(--text-h)] text-lg leading-none"
          >
            ×
          </button>
        </div>

        <p className="text-[var(--text)] leading-relaxed mb-4">
          Most notes apps are where knowledge goes to be forgotten. LearnByInterrogation turns
          whatever you write — maths, code, philosophy, anything — into a living knowledge
          graph, then puts Socrates in the room with you. It reads your own notes, finds the
          gaps, contradictions and undefined ideas, and interrogates you until you actually
          understand what you wrote.
        </p>
        <p className="text-[var(--text)] leading-relaxed mb-6">
          Everything — your notes, embeddings and the graph — stays local in your browser.
          Only the questions themselves are generated by an AI model you connect with your own
          API key.
        </p>

        <div className="border-l-2 border-[var(--accent)] bg-[var(--accent-bg)] rounded-r-lg px-4 py-3">
          <p className="italic text-sm text-[var(--text-h)]">
            "The unexamined note is not worth keeping. Let the graph show you what you don't
            yet know — and let the questions make you own it."
          </p>
        </div>

        <button
          onClick={onClose}
          className="mt-6 w-full rounded-lg bg-[var(--accent)] hover:bg-[var(--accent-2)] text-white font-medium py-2.5 transition-colors"
        >
          ✦ Got it
        </button>
      </div>
    </div>
  );
}
